### ISSUE TITLE
想请教下为什么一直显示“GoWebDav”未运行

### ISSUE THREAD

**Issue by hellodk34** [immortalwrt-collections/openwrt-gowebdav#7]
程序像是无法启动，通过 `/etc/init.d/gowebdav restart` 重启也没有帮助。可以帮忙看看吗。

查看 gowebdav 版本

```
# opkg list-installed |grep webdav
gowebdav - 0.0.4-1
luci-app-gowebdav - 1.0-1
luci-i18n-gowebdav-zh-cn - 1.0-1
```

目前的 luci 配置如下 `cat /etc/config/gowebdav`

```

config gowebdav 'config'
	option listen_port '6086'
	option read_only '0'
	option allow_wan '0'
	option use_https '0'
	option username 'xxx'
	option password 'xxx'
	option root_dir '/mnt/xxx'
	option enable '0'
```

`cat /etc/openwrt_release` 查看 OpenWrt 发行信息如下

``` 
DISTRIB_ID='ImmortalWrt'
DISTRIB_RELEASE='18.06-k5.4-SNAPSHOT'
DISTRIB_REVISION='r12158-346e3cbd39'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='ImmortalWrt 18.06-k5.4-SNAPSHOT r12158-346e3cbd39 (2022-06-06)'
DISTRIB_TAINTS='busybox'
```

`cat /etc/openwrt_version` 查看到的版本如下

```
r12158-346e3cbd39
```

**Comment by yeungxing** [comment]
我也是这个问题，无论怎么设置一直都是 GoWebDav 未运行 （安装完默认配置直接保存应用）

通过 /etc/init.d/gowebdav restart 重启   显示： Terminated
版本：
# opkg list-installed |grep webdav
gowebdav - 0.0.4-26
luci-app-gowebdav - git-22.147.57852-d7e4f23

cat /etc/config/gowebdav

config gowebdav 'config'
        option listen_port '6086'
        option username 'user'
        option password 'pass'
        option root_dir '/mnt'
        option read_only '0'
        option allow_wan '0'
        option use_https '0'
        option enable '1'


 cat /etc/openwrt_release
DISTRIB_ID='1004'
DISTRIB_RELEASE='22.03.0-rc2'
DISTRIB_REVISION='06.06.2022'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION="OpenWrt 06.06.2022 by Kiddin'"
DISTRIB_TAINTS='busybox'

cat /etc/openwrt_version
06.06.2022

**Comment by hellodk34** [comment]
@yeungxing  谢谢。
